// <auto-generated />
using System;
using HotelManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace hotelManagamentFinal.Migrations
{
    [DbContext(typeof(HotelManagementContext))]
    [Migration("20250115202319_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelManagement.Models.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action");

                    b.Property<string>("Pershkrim")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("pershkrim");

                    b.HasKey("Id")
                        .HasName("PK__Action__3213E83FDBDBB588");

                    b.ToTable("Action", (string)null);
                });

            modelBuilder.Entity("HotelManagement.Models.Akomodim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adults")
                        .HasColumnType("int")
                        .HasColumnName("adults");

                    b.Property<decimal>("Cmim")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("cmim");

                    b.Property<string>("Emer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("emer");

                    b.Property<int?>("Femije")
                        .HasColumnType("int")
                        .HasColumnName("femije");

                    b.Property<bool>("KrevatExtra")
                        .HasColumnType("bit")
                        .HasColumnName("krevat_extra");

                    b.HasKey("Id")
                        .HasName("PK__Akomodim__3213E83F0F7E9F72");

                    b.ToTable("Akomodim", (string)null);
                });

            modelBuilder.Entity("HotelManagement.Models.Dhome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Kat")
                        .HasColumnType("int")
                        .HasColumnName("kat");

                    b.Property<string>("NumerDhome")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("numer_dhome");

                    b.Property<int>("TipDhome")
                        .HasColumnType("int")
                        .HasColumnName("tip_dhome");

                    b.HasKey("Id")
                        .HasName("PK__Dhome__3213E83FADA7053C");

                    b.HasIndex("TipDhome");

                    b.ToTable("Dhome", (string)null);
                });

            modelBuilder.Entity("HotelManagement.Models.ExtraService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Emer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("emer");

                    b.Property<string>("Pershkrim")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("pershkrim");

                    b.HasKey("Id")
                        .HasName("PK__Extra_Se__3213E83F74321873");

                    b.ToTable("Extra_Service", (string)null);
                });

            modelBuilder.Entity("HotelManagement.Models.Fature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateFature")
                        .HasColumnType("date")
                        .HasColumnName("date_fature");

                    b.Property<int>("Rezervim")
                        .HasColumnType("int")
                        .HasColumnName("rezervim");

                    b.Property<decimal>("RoomCharge")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("room_charge");

                    b.Property<decimal?>("ServiceCharge")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("service_charge");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("PK__Fature__3213E83F24F7FE2A");

                    b.HasIndex("Rezervim");

                    b.ToTable("Fature", (string)null);
                });

            modelBuilder.Entity("HotelManagement.Models.Pagese", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DatePagese")
                        .HasColumnType("date")
                        .HasColumnName("date_pagese");

                    b.Property<int>("Fature")
                        .HasColumnType("int")
                        .HasColumnName("fature");

                    b.Property<string>("Menyre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("menyre");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("PK__Pagese__3213E83FDF1DDDFC");

                    b.HasIndex("Fature");

                    b.ToTable("Pagese", (string)null);
                });

            modelBuilder.Entity("HotelManagement.Models.Privilegj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int")
                        .HasColumnName("action");

                    b.Property<int>("Rol")
                        .HasColumnType("int")
                        .HasColumnName("rol");

                    b.HasKey("Id")
                        .HasName("PK__Privileg__3213E83FA168C80C");

                    b.HasIndex("Action");

                    b.HasIndex("Rol");

                    b.ToTable("Privilegj", (string)null);
                });

            modelBuilder.Entity("HotelManagement.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Pershkrim")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("pershkrim");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int>("User")
                        .HasColumnType("int")
                        .HasColumnName("user");

                    b.HasKey("Id")
                        .HasName("PK__Review__3213E83F340D5072");

                    b.HasIndex("User");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("HotelManagement.Models.Rezervim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Akomodim")
                        .HasColumnType("int")
                        .HasColumnName("akomodim");

                    b.Property<DateOnly>("CheckIn")
                        .HasColumnType("date")
                        .HasColumnName("check_in");

                    b.Property<DateOnly>("CheckOut")
                        .HasColumnType("date")
                        .HasColumnName("check_out");

                    b.Property<decimal>("Cmim")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("cmim");

                    b.Property<int>("Dhome")
                        .HasColumnType("int")
                        .HasColumnName("dhome");

                    b.Property<int?>("RoomRate")
                        .HasColumnType("int")
                        .HasColumnName("room_rate");

                    b.Property<int>("User")
                        .HasColumnType("int")
                        .HasColumnName("user");

                    b.HasKey("Id")
                        .HasName("PK__Rezervim__3213E83F284C1B56");

                    b.HasIndex("Akomodim");

                    b.HasIndex("Dhome");

                    b.HasIndex("RoomRate");

                    b.HasIndex("User");

                    b.ToTable("Rezervim", (string)null);
                });

            modelBuilder.Entity("HotelManagement.Models.RezervimService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Rezervim")
                        .HasColumnType("int")
                        .HasColumnName("rezervim");

                    b.Property<int>("Sasi")
                        .HasColumnType("int")
                        .HasColumnName("sasi");

                    b.Property<int>("Sherbim")
                        .HasColumnType("int")
                        .HasColumnName("sherbim");

                    b.HasKey("Id")
                        .HasName("PK__Rezervim__3213E83FD24DA3E8");

                    b.HasIndex("Rezervim");

                    b.ToTable("Rezervim_Service", (string)null);
                });

            modelBuilder.Entity("HotelManagement.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmerRoli")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("emer_roli");

                    b.HasKey("Id")
                        .HasName("PK__Role__3213E83FCD91C39A");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("HotelManagement.Models.RoomRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CmimBaze")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("cmim_baze");

                    b.Property<string>("Emer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("emer");

                    b.HasKey("Id")
                        .HasName("PK__Room_Rat__3213E83FA8C6F001");

                    b.ToTable("Room_Rate", (string)null);
                });

            modelBuilder.Entity("HotelManagement.Models.RoomRateRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<decimal?>("HolidayPricing")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("holiday_pricing");

                    b.Property<int>("RoomRateId")
                        .HasColumnType("int")
                        .HasColumnName("room_rate_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<decimal?>("WeekendPricing")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("weekend_pricing");

                    b.HasKey("Id")
                        .HasName("PK__Room_Rat__3213E83FF0D65227");

                    b.HasIndex("RoomRateId");

                    b.ToTable("Room_Rate_Ranges", (string)null);
                });

            modelBuilder.Entity("HotelManagement.Models.TipDhome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cmim")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("cmim");

                    b.Property<string>("Emer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("emer");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int")
                        .HasColumnName("kapacitet");

                    b.Property<string>("Pershkrim")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("pershkrim");

                    b.Property<decimal?>("Siperfaqe")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("siperfaqe");

                    b.HasKey("Id")
                        .HasName("PK__Tip_dhom__3213E83F8FAA4439");

                    b.ToTable("Tip_dhome", (string)null);
                });

            modelBuilder.Entity("HotelManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Emer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("emer");

                    b.Property<string>("Mbiemer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mbiemer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("password");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("PK__User__3213E83FD058E8B0");

                    b.HasIndex(new[] { "Email" }, "UQ__User__AB6E61640BA26EED")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("HotelManagement.Models.Dhome", b =>
                {
                    b.HasOne("HotelManagement.Models.TipDhome", "TipDhomeNavigation")
                        .WithMany("Dhomes")
                        .HasForeignKey("TipDhome")
                        .IsRequired()
                        .HasConstraintName("FK__Dhome__tip_dhome__47DBAE45");

                    b.Navigation("TipDhomeNavigation");
                });

            modelBuilder.Entity("HotelManagement.Models.Fature", b =>
                {
                    b.HasOne("HotelManagement.Models.Rezervim", "RezervimNavigation")
                        .WithMany("Fatures")
                        .HasForeignKey("Rezervim")
                        .IsRequired()
                        .HasConstraintName("FK__Fature__rezervim__5BE2A6F2");

                    b.Navigation("RezervimNavigation");
                });

            modelBuilder.Entity("HotelManagement.Models.Pagese", b =>
                {
                    b.HasOne("HotelManagement.Models.Fature", "FatureNavigation")
                        .WithMany("Pageses")
                        .HasForeignKey("Fature")
                        .IsRequired()
                        .HasConstraintName("FK__Pagese__fature__5EBF139D");

                    b.Navigation("FatureNavigation");
                });

            modelBuilder.Entity("HotelManagement.Models.Privilegj", b =>
                {
                    b.HasOne("HotelManagement.Models.Action", "ActionNavigation")
                        .WithMany("Privilegjs")
                        .HasForeignKey("Action")
                        .IsRequired()
                        .HasConstraintName("FK__Privilegj__actio__3E52440B");

                    b.HasOne("HotelManagement.Models.Role", "RolNavigation")
                        .WithMany("Privilegjs")
                        .HasForeignKey("Rol")
                        .IsRequired()
                        .HasConstraintName("FK__Privilegj__rol__3F466844");

                    b.Navigation("ActionNavigation");

                    b.Navigation("RolNavigation");
                });

            modelBuilder.Entity("HotelManagement.Models.Review", b =>
                {
                    b.HasOne("HotelManagement.Models.User", "UserNavigation")
                        .WithMany("Reviews")
                        .HasForeignKey("User")
                        .IsRequired()
                        .HasConstraintName("FK__Review__user__4222D4EF");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("HotelManagement.Models.Rezervim", b =>
                {
                    b.HasOne("HotelManagement.Models.Akomodim", "AkomodimNavigation")
                        .WithMany("Rezervims")
                        .HasForeignKey("Akomodim")
                        .HasConstraintName("FK__Rezervim__akomod__5441852A");

                    b.HasOne("HotelManagement.Models.Dhome", "DhomeNavigation")
                        .WithMany("Rezervims")
                        .HasForeignKey("Dhome")
                        .IsRequired()
                        .HasConstraintName("FK__Rezervim__dhome__52593CB8");

                    b.HasOne("HotelManagement.Models.RoomRate", "RoomRateNavigation")
                        .WithMany("Rezervims")
                        .HasForeignKey("RoomRate")
                        .HasConstraintName("FK__Rezervim__room_r__534D60F1");

                    b.HasOne("HotelManagement.Models.User", "UserNavigation")
                        .WithMany("Rezervims")
                        .HasForeignKey("User")
                        .IsRequired()
                        .HasConstraintName("FK__Rezervim__user__5165187F");

                    b.Navigation("AkomodimNavigation");

                    b.Navigation("DhomeNavigation");

                    b.Navigation("RoomRateNavigation");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("HotelManagement.Models.RezervimService", b =>
                {
                    b.HasOne("HotelManagement.Models.Rezervim", "RezervimNavigation")
                        .WithMany("RezervimServices")
                        .HasForeignKey("Rezervim")
                        .IsRequired()
                        .HasConstraintName("FK__Rezervim___rezer__571DF1D5");

                    b.Navigation("RezervimNavigation");
                });

            modelBuilder.Entity("HotelManagement.Models.RoomRateRange", b =>
                {
                    b.HasOne("HotelManagement.Models.RoomRate", "RoomRate")
                        .WithMany("RoomRateRanges")
                        .HasForeignKey("RoomRateId")
                        .IsRequired()
                        .HasConstraintName("FK__Room_Rate__room___4E88ABD4");

                    b.Navigation("RoomRate");
                });

            modelBuilder.Entity("HotelManagement.Models.Action", b =>
                {
                    b.Navigation("Privilegjs");
                });

            modelBuilder.Entity("HotelManagement.Models.Akomodim", b =>
                {
                    b.Navigation("Rezervims");
                });

            modelBuilder.Entity("HotelManagement.Models.Dhome", b =>
                {
                    b.Navigation("Rezervims");
                });

            modelBuilder.Entity("HotelManagement.Models.Fature", b =>
                {
                    b.Navigation("Pageses");
                });

            modelBuilder.Entity("HotelManagement.Models.Rezervim", b =>
                {
                    b.Navigation("Fatures");

                    b.Navigation("RezervimServices");
                });

            modelBuilder.Entity("HotelManagement.Models.Role", b =>
                {
                    b.Navigation("Privilegjs");
                });

            modelBuilder.Entity("HotelManagement.Models.RoomRate", b =>
                {
                    b.Navigation("Rezervims");

                    b.Navigation("RoomRateRanges");
                });

            modelBuilder.Entity("HotelManagement.Models.TipDhome", b =>
                {
                    b.Navigation("Dhomes");
                });

            modelBuilder.Entity("HotelManagement.Models.User", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Rezervims");
                });
#pragma warning restore 612, 618
        }
    }
}
